#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Login
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="UserLogin")]
	public partial class DiagramacaoDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InserttbLogando(tbLogando instance);
    partial void UpdatetbLogando(tbLogando instance);
    partial void DeletetbLogando(tbLogando instance);
    partial void InserttbVoce(tbVoce instance);
    partial void UpdatetbVoce(tbVoce instance);
    partial void DeletetbVoce(tbVoce instance);
    #endregion
		
		public DiagramacaoDataContext() : 
				base(global::Login.Properties.Settings.Default.UserLoginConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public DiagramacaoDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DiagramacaoDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DiagramacaoDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DiagramacaoDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tbLogando> tbLogandos
		{
			get
			{
				return this.GetTable<tbLogando>();
			}
		}
		
		public System.Data.Linq.Table<tbVoce> tbVoces
		{
			get
			{
				return this.GetTable<tbVoce>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbLogando")]
	public partial class tbLogando : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CodUser;
		
		private string _NomeUser;
		
		private string _SenhaUser;
		
		private EntitySet<tbVoce> _tbVoces;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodUserChanging(int value);
    partial void OnCodUserChanged();
    partial void OnNomeUserChanging(string value);
    partial void OnNomeUserChanged();
    partial void OnSenhaUserChanging(string value);
    partial void OnSenhaUserChanged();
    #endregion
		
		public tbLogando()
		{
			this._tbVoces = new EntitySet<tbVoce>(new Action<tbVoce>(this.attach_tbVoces), new Action<tbVoce>(this.detach_tbVoces));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodUser", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CodUser
		{
			get
			{
				return this._CodUser;
			}
			set
			{
				if ((this._CodUser != value))
				{
					this.OnCodUserChanging(value);
					this.SendPropertyChanging();
					this._CodUser = value;
					this.SendPropertyChanged("CodUser");
					this.OnCodUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NomeUser", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string NomeUser
		{
			get
			{
				return this._NomeUser;
			}
			set
			{
				if ((this._NomeUser != value))
				{
					this.OnNomeUserChanging(value);
					this.SendPropertyChanging();
					this._NomeUser = value;
					this.SendPropertyChanged("NomeUser");
					this.OnNomeUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SenhaUser", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string SenhaUser
		{
			get
			{
				return this._SenhaUser;
			}
			set
			{
				if ((this._SenhaUser != value))
				{
					this.OnSenhaUserChanging(value);
					this.SendPropertyChanging();
					this._SenhaUser = value;
					this.SendPropertyChanged("SenhaUser");
					this.OnSenhaUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbLogando_tbVoce", Storage="_tbVoces", ThisKey="CodUser", OtherKey="CodVoce")]
		public EntitySet<tbVoce> tbVoces
		{
			get
			{
				return this._tbVoces;
			}
			set
			{
				this._tbVoces.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbVoces(tbVoce entity)
		{
			this.SendPropertyChanging();
			entity.tbLogando = this;
		}
		
		private void detach_tbVoces(tbVoce entity)
		{
			this.SendPropertyChanging();
			entity.tbLogando = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbVoce")]
	public partial class tbVoce : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CodVoce;
		
		private string _DtNascimento;
		
		private string _IdadeVoce;
		
		private string _NomeVoce;
		
		private string _DtAtual;
		
		private System.Data.Linq.Binary _FotoVoce;
		
		private string _EnderecoVoce;
		
		private string _TelFixo;
		
		private string _Operadora;
		
		private string _TelCel;
		
		private string _Texto;
		
		private EntityRef<tbLogando> _tbLogando;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodVoceChanging(int value);
    partial void OnCodVoceChanged();
    partial void OnDtNascimentoChanging(string value);
    partial void OnDtNascimentoChanged();
    partial void OnIdadeVoceChanging(string value);
    partial void OnIdadeVoceChanged();
    partial void OnNomeVoceChanging(string value);
    partial void OnNomeVoceChanged();
    partial void OnDtAtualChanging(string value);
    partial void OnDtAtualChanged();
    partial void OnFotoVoceChanging(System.Data.Linq.Binary value);
    partial void OnFotoVoceChanged();
    partial void OnEnderecoVoceChanging(string value);
    partial void OnEnderecoVoceChanged();
    partial void OnTelFixoChanging(string value);
    partial void OnTelFixoChanged();
    partial void OnOperadoraChanging(string value);
    partial void OnOperadoraChanged();
    partial void OnTelCelChanging(string value);
    partial void OnTelCelChanged();
    partial void OnTextoChanging(string value);
    partial void OnTextoChanged();
    #endregion
		
		public tbVoce()
		{
			this._tbLogando = default(EntityRef<tbLogando>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodVoce", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CodVoce
		{
			get
			{
				return this._CodVoce;
			}
			set
			{
				if ((this._CodVoce != value))
				{
					if (this._tbLogando.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCodVoceChanging(value);
					this.SendPropertyChanging();
					this._CodVoce = value;
					this.SendPropertyChanged("CodVoce");
					this.OnCodVoceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DtNascimento", DbType="VarChar(8) NOT NULL", CanBeNull=false)]
		public string DtNascimento
		{
			get
			{
				return this._DtNascimento;
			}
			set
			{
				if ((this._DtNascimento != value))
				{
					this.OnDtNascimentoChanging(value);
					this.SendPropertyChanging();
					this._DtNascimento = value;
					this.SendPropertyChanged("DtNascimento");
					this.OnDtNascimentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdadeVoce", DbType="VarChar(8) NOT NULL", CanBeNull=false)]
		public string IdadeVoce
		{
			get
			{
				return this._IdadeVoce;
			}
			set
			{
				if ((this._IdadeVoce != value))
				{
					this.OnIdadeVoceChanging(value);
					this.SendPropertyChanging();
					this._IdadeVoce = value;
					this.SendPropertyChanged("IdadeVoce");
					this.OnIdadeVoceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NomeVoce", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string NomeVoce
		{
			get
			{
				return this._NomeVoce;
			}
			set
			{
				if ((this._NomeVoce != value))
				{
					this.OnNomeVoceChanging(value);
					this.SendPropertyChanging();
					this._NomeVoce = value;
					this.SendPropertyChanged("NomeVoce");
					this.OnNomeVoceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DtAtual", DbType="VarChar(8) NOT NULL", CanBeNull=false)]
		public string DtAtual
		{
			get
			{
				return this._DtAtual;
			}
			set
			{
				if ((this._DtAtual != value))
				{
					this.OnDtAtualChanging(value);
					this.SendPropertyChanging();
					this._DtAtual = value;
					this.SendPropertyChanged("DtAtual");
					this.OnDtAtualChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FotoVoce", DbType="Image NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary FotoVoce
		{
			get
			{
				return this._FotoVoce;
			}
			set
			{
				if ((this._FotoVoce != value))
				{
					this.OnFotoVoceChanging(value);
					this.SendPropertyChanging();
					this._FotoVoce = value;
					this.SendPropertyChanged("FotoVoce");
					this.OnFotoVoceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EnderecoVoce", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string EnderecoVoce
		{
			get
			{
				return this._EnderecoVoce;
			}
			set
			{
				if ((this._EnderecoVoce != value))
				{
					this.OnEnderecoVoceChanging(value);
					this.SendPropertyChanging();
					this._EnderecoVoce = value;
					this.SendPropertyChanged("EnderecoVoce");
					this.OnEnderecoVoceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TelFixo", DbType="VarChar(18) NOT NULL", CanBeNull=false)]
		public string TelFixo
		{
			get
			{
				return this._TelFixo;
			}
			set
			{
				if ((this._TelFixo != value))
				{
					this.OnTelFixoChanging(value);
					this.SendPropertyChanging();
					this._TelFixo = value;
					this.SendPropertyChanged("TelFixo");
					this.OnTelFixoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Operadora", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string Operadora
		{
			get
			{
				return this._Operadora;
			}
			set
			{
				if ((this._Operadora != value))
				{
					this.OnOperadoraChanging(value);
					this.SendPropertyChanging();
					this._Operadora = value;
					this.SendPropertyChanged("Operadora");
					this.OnOperadoraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TelCel", DbType="VarChar(18) NOT NULL", CanBeNull=false)]
		public string TelCel
		{
			get
			{
				return this._TelCel;
			}
			set
			{
				if ((this._TelCel != value))
				{
					this.OnTelCelChanging(value);
					this.SendPropertyChanging();
					this._TelCel = value;
					this.SendPropertyChanged("TelCel");
					this.OnTelCelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Texto", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Texto
		{
			get
			{
				return this._Texto;
			}
			set
			{
				if ((this._Texto != value))
				{
					this.OnTextoChanging(value);
					this.SendPropertyChanging();
					this._Texto = value;
					this.SendPropertyChanged("Texto");
					this.OnTextoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbLogando_tbVoce", Storage="_tbLogando", ThisKey="CodVoce", OtherKey="CodUser", IsForeignKey=true)]
		public tbLogando tbLogando
		{
			get
			{
				return this._tbLogando.Entity;
			}
			set
			{
				tbLogando previousValue = this._tbLogando.Entity;
				if (((previousValue != value) 
							|| (this._tbLogando.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbLogando.Entity = null;
						previousValue.tbVoces.Remove(this);
					}
					this._tbLogando.Entity = value;
					if ((value != null))
					{
						value.tbVoces.Add(this);
						this._CodVoce = value.CodUser;
					}
					else
					{
						this._CodVoce = default(int);
					}
					this.SendPropertyChanged("tbLogando");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
